- name: variables
  hosts: local
  connection: local
  vars: #task level vars (global)
   COURSE: "DEVOPS"
   DURATION: "120 HOURS"

  tasks:
    - name: print the task(global) variables
      ansible.builtin.debug:
        msg: " course is {{COURSE}} ,duration {{DURATION}}  "

  tasks:
    vars:
      TRAINER: Govardhan
      COURSE: ansible
      DURATION: 5 Hrs
    - name: print the task(global) variables
      ansible.builtin.debug:
        msg: " course is {{COURSE}} ,duration {{DURATION}} , {{TRAINER}} "      