- name: variables
  hosts: local
  connection: local
  vars: #play level vars (global)
   COURSE: "DEVOPS"
   DURATION: "120 HOURS"

  tasks:
    - name: print the play level variables
      ansible.builtin.debug:
        msg: " course is {{COURSE}} ,duration {{DURATION}}  "

  
    - name: print the task level vars
      vars:
        TRAINER: Govardhan
        DURATION: "5 hrs"
      ansible.builtin.debug:
       msg: " course is {{COURSE}} ,duration {{DURATION}} ,trainer {{TRAINER}}  "