- name: variables from files
  hosts: local
  connection: local
  tasks:
    - name: vars from files
      ansible.builtin.debug:
        msg: "course is {{COURSE}} ,duration is {{DURATION}} trainer is {{TRAINER}}"