- name: variables from prompt
  hosts: local
  connection: local
  vars_prompt:
    - name: COURSE
      prompt: please enter course name
      private: false # it is not confidential info

    - name: DURATION
      prompt: please enter the duration
      private: false

    - name: TRAINER
      prompt: please enter trainer name
       

  tasks:
    - name: print prompt variables
      ansible.builtin.debug:
        msg: "course is {{COURSE}} ,duration is {{DURATION}} trainer is {{TRAINER}}"
